server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5434/barbershop_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=barbershop_super_secret_key_2026_segura
app.jwt.expiration-ms=86400000

app.frontend.url=http://localhost:3000
app.api.url=http://localhost:8080

app.business.name=ElPipeBarber
app.business.address=La Galaxia 2292, Maipu
app.business.phone=+56 9 9809 8449

# ?? Seeder Admin 1: Felipe (dueño y barbero) ?????????????????????????????????
# NOTA: en pruebas locales ambos apuntan a danielorlandodiaz14@gmail.com
#       Revertir a blade.barberia1@gmail.com antes de subir a producción
app.seed.admin.email=danielorlandodiaz14@gmail.com
app.seed.admin.password=Admin123!
app.seed.admin.name=Felipe Eliecer

# ?? Seeder Admin 2: Daniel (soporte técnico) ??????????????????????????????????
app.seed.admin2.email=danielorlandodiaz14@gmail.com
app.seed.admin2.password=Admin123!
app.seed.admin2.name=Soporte Tecnico

# ?? Barbero vinculado a agenda y emails ???????????????????????????????????????
# En pruebas: apunta a danielorlandodiaz14@gmail.com para recibir emails de prueba
# En producción: cambiar a blade.barberia1@gmail.com
app.seed.barber.email=danielorlandodiaz14@gmail.com
app.seed.barber.name=Felipe Eliecer

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.org.hibernate.SQL=DEBUG
logging.level.com.barbershop=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=danielorlandodiaz14@gmail.com
spring.mail.password=dgnfnzallpthsydg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.task.scheduling.enabled=true
