# ?? SERVIDOR ??????????????????????????????????????????
server.port=8080

# ?? BASE DE DATOS SUPABASE ????????????????????????????
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.whyynlngtdtrmopzxyvy
spring.datasource.password=TU_PASSWORD_SUPABASE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SET search_path TO public

# ?? JPA / HIBERNATE ???????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ?? JWT ???????????????????????????????????????????????
app.jwt.secret=barbershop_super_secret_key_2026_segura
app.jwt.expiration-ms=86400000

# ?? FRONTEND URL (CORS) ???????????????????????????????
# se actualizará con la URL de Vercel después
app.frontend.url=https://barbershop-frontend.vercel.app

# ?? STRIPE ???????????????????????????????????????????
stripe.secret.key=sk_test_reemplazame

# ?? SWAGGER ??????????????????????????????????????????
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ?? LOGS ?????????????????????????????????????????????
logging.level.org.hibernate.SQL=WARN
logging.level.com.barbershop=INFO